server:
  servlet:
    contextPath: /
    mappings:
      properties: "/1.0/properties"
      resolve: "/1.0/identifiers"
      methods: "/1.0/methods"
      testIdentifiers: "/1.0/testIdentifiers"
      traits: "/1.0/traits"
  port: "8080"

spring:
  profiles:
    active: ${uniresolver_web_spring_profiles_active:default}

uniresolver:
  drivers:
    - pattern: "^(did:btc1:.+)$"
      url: http://driver-did-btc1:8080/
      supportsOptions: true
      testIdentifiers:
        - did:btc1:k1qypcylxwhf8sykn2dztm6z8lxm43kwkyzf07qmp9jafv3zfntmpwtks9hmnrw
        - did:btc1:k1qypdnfyh7j8z87wk3vylqaz9t8psnkws8k5e2ccl9c0zqwwt5uyjeeg7f3knj
