version: "3.6"

services:
  ipfs:
    image: ipfs/kubo:release
    ports:
      - "4001:4001"
      - "5001:5001"
  driver-did-btc1:
    image: universalresolver/driver-did-btc1:latest
    ports:
      - "8081:8080"
    environment:
      uniresolver_driver_did_btc1_bitcoinConnection: btcd
      uniresolver_driver_did_btc1_rpcUrlMainnet: http://user:pass@localhost:8332/
      uniresolver_driver_did_btc1_rpcUrlTestnet: http://user:pass@localhost:18332/
      uniresolver_driver_did_btc1_rpcCertMainnet:
      uniresolver_driver_did_btc1_rpcCertTestnet:
      uniresolver_driver_did_btc1_ipfs: /dns4/ipfs/tcp/5001
