version: "3.6"

services:
  uni-resolver-web:
    container_name: uni-resolver-web
    image: universalresolver/uni-resolver-web:latest
    environment:
      spring.config.location: file:/opt/config/application.yml
    volumes:
      - ./application-universal-resolver.yml:/opt/config/application.yml
    ports:
      - "8080:8080"
  driver-did-btc1:
    container_name: driver-did-btc1
    image: universalresolver/driver-did-btc1:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      uniresolver_driver_did_btc1_bitcoinConnection: bitcoind
      uniresolver_driver_did_btc1_rpcUrlMainnet: http://user:pass@172.17.42.1:8332/
      uniresolver_driver_did_btc1_rpcUrlSignet: http://polaruser:polarpass@backend1.universal-resolver:18443/
      uniresolver_driver_did_btc1_rpcUrlRegtest: http://polaruser:polarpass@backend1.universal-resolver:18443/
      uniresolver_driver_did_btc1_rpcUrlTestnet: http://user:pass@172.17.42.1:18332/
      uniresolver_driver_did_btc1_rpcCertMainnet:
      uniresolver_driver_did_btc1_rpcCertSignet:
      uniresolver_driver_did_btc1_rpcCertRegtest:
      uniresolver_driver_did_btc1_rpcCertTestnet:
      uniresolver_driver_did_btc1_ipfs: /dns4/ipfs/tcp/5001
    ports:
      - "10081:8080"
  ipfs:
    container_name: ipfs
    image: ipfs/kubo:release
    ports:
      - "4001:4001"
      - "5001:5001"
